# Generated by Django 4.1.5 on 2023-08-10 12:13

from django.db import migrations, models
import user_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.CharField(default='', max_length=100, null=True, unique=True)),
                ('user_node_id', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user_manager.models.UserModuleManager()),
            ],
        ),
    ]
