# Generated by Django 4.1.5 on 2023-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
