# Generated by Django 4.1.5 on 2023-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_remove_usermanager_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='is_staff',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='usermanager',
            name='supervisor_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
